#!/bin/bash

# Uses the currently installed jetty-runner jar from your local M2 repository
# to run a war file from the filesystem

: ${REPO=$HOME/.m2/repository}

function artifact-file(){
    AID=$1
    GID=$2
    VID=$3

    ARTIFACT=$REPO/${GID//.//}/$AID/$VID/$AID-$VID.jar
}

function ensure-dependency(){
    AID=$1
    GID=$2
    VID=$3

    artifact-file $AID $GID $VID
    if [ ! -f $ARTIFACT ]
    then
        echo "$GID/$AID v$VID is missing, downloading"
        mvn dependency:get -DartifactId=$AID -DgroupId=$GID -Dversion=$VID -DrepoUrl=http://repo1.maven.org/maven2 > /dev/null
    fi
}

function run-war(){
    ensure-dependency h2-support tk.skuro.alfresco 1.6
    ensure-dependency jetty-runner org.eclipse.jetty 9.2.1.v20140609

    JETTY_RUNNER=$ARTIFACT
    echo "Running Jetty"
    java -jar $JETTY_RUNNER $@
}

run-war --lib ~/.m2/repository/com/h2database/h2/1.3.174 --lib ~/.m2/repository/tk/skuro/alfresco/h2-support/1.6  --config jetty.xml target/alfresco-4.2.c.war
