#!/bin/bash
#
# We actually want to run  this straight from leinigen
#
# Uses the currently installed jetty-runner jar from your local M2 repository
# to run a war file from the filesystem
# 9.2.2.v20140723
# 9.2.3.v20140905
JETTY_VERSION=9.2.3.v20140905

: ${REPO=$HOME/.m2/repository}
: ${JAVA_OPTS='-Xmx512m -XX:MaxPermSize=256m'}

function artifact-file(){
    AID=$1
    GID=$2
    VID=$3

    ARTIFACT=$REPO/${GID//.//}/$AID/$VID/$AID-$VID.jar
}

function run-war(){
    artifact-file jetty-runner org.eclipse.jetty ${JETTY_VERSION}
    JETTY_RUNNER=$ARTIFACT
    echo "Running Jetty"
    java $JAVA_OPTS -jar $JETTY_RUNNER $@
}

# run-war --lib ~/.m2/repository/com/h2database/h2/1.3.174 --lib ~/.m2/repository/tk/skuro/alfresco/h2-support/1.6  --config jetty.xml target/alfresco-4.2.c.war

run-war --lib ~/.m2/repository/com/h2database/h2/1.3.174 --lib ~/.m2/repository/tk/skuro/alfresco/h2-support/1.8  --config jetty.xml jetty-webcontext.xml
